### ISSUE TITLE
I can read about standalone Decision evaluation

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-platform-docs#1516]
Zeebe will support standalone Decision evaluation (see https://github.com/camunda/zeebe/issues/11037). We will need to document this feature.

**Tasks:**
- [x] Document the call in the [Zeebe API (gRPC)](https://docs.camunda.io/docs/apis-clients/grpc/)
    - Document the different responses:
       - [x] Invalid command - rejection
       - [x] Evaluation failure - valid response with failure message
       - [x] Evaluation success - valid response with result
    - Document that if both the Decision ID and KEY are provided, the ID takes presedence.
- [x] Add an example for the Java client ([similar to this maybe](https://docs.camunda.io/docs/apis-clients/java-client-examples/process-instance-create/))
- [x] Mention the new API in [the Business rule task docs](https://docs.camunda.io/docs/components/modeler/bpmn/business-rule-tasks/)

**Blocked by**
* https://github.com/camunda/zeebe/issues/11047
* https://github.com/camunda/zeebe/issues/11048

**Comment by koevskinikola** [comment]
Hi @akeller, do you think there is any other place where documentation on this feature would be useful?

**Comment by akeller** [comment]
@koevskinikola perhaps a mention on [this page](https://docs.camunda.io/docs/components/modeler/bpmn/business-rule-tasks/) since it's the current way users know decisions can be evaluated.
