### ISSUE TITLE
Error catch events without error code (catch-all Error events)

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-platform-docs#1579]
### Description
With https://github.com/camunda/zeebe/issues/11126, Zeebe now supports Error catch events without an error code.

This enables users to model a specific response for a known escalation code, and a general response for unknown escalation codes.

### Tasks
Add a paragraph in the existing [catching the error](https://docs.camunda.io/docs/next/components/modeler/bpmn/error-events/#catching-the-error) section of the documentation to make users aware that Error catch events without error codes (catch-all) are possible.

The paragraph should describe the behavior of catch-all Error event:
- [x] There can be only one per scope
- [x] A catch-all Error event will catch all Errors that bubble up in it's scope.
- [x] If an Error catch event with a defined error code exists, it will be preferred over the catch-all Error event for Errors with that code.

### Blocked by
* https://github.com/camunda/zeebe/issues/11126
