### ISSUE TITLE
Documentation review: Modeler SaaS

### ISSUE THREAD

**Issue by christinaausley** [camunda/camunda-platform-docs#2120]
## MVP

Modeler SaaS section is reviewed, suggestions are documented, and issues are created and prioritized as appropriate for Modeler team to execute at capacity, with DevEx review/assistance.

## Overview

Related to https://github.com/camunda/developer-experience/issues/63.

We've outlined a [document](https://docs.google.com/document/d/12eLluv7tJQOOJlUNp8aRjN95pBvpdsrVlJzyXVWKNC4/edit?usp=sharing) to track our review progress, and will update the Modeler team accordingly upon completion of review.

## Breadkdown

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/web-modeler/issues/5721
- [ ] https://github.com/bpmn-io/internal-docs/issues/805
- [ ] https://github.com/camunda/camunda-platform-docs/pull/2427
```

**Comment by christinaausley** [comment]
Note that @jwulf and I are meeting the following dates this quarter to review Modeler SaaS documentation for suggested improvements:
- May 25
- May 30
- June 1

**Comment by christinaausley** [comment]
@jwulf and I have regularly scheduled meetings every Monday and Wednesday for 45-minute increments through July to wrap up Modeler review, and begin launching urgent issues as appropriate with the @camunda/modeling team.

**Comment by nikku** [comment]
@christinaausley You can reach out to the Web Modeler Team via @camunda/web-modeler-cawemo.

**Comment by christinaausley** [comment]
This PR is about wrapped up -- just need final approval 👍
