### ISSUE TITLE
Archive v0.25

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#2183]
Archive version 0.25.

## Progress

```[tasklist]
### Tasks
- [x] https://github.com/camunda/camunda-platform-docs/pull/2165
- [x] https://github.com/camunda/camunda-platform-docs/pull/2166
- [x] https://github.com/camunda/camunda-platform-docs/pull/2167
- [x] https://github.com/camunda/camunda-platform-docs/pull/2171
- [x] https://github.com/camunda/camunda-platform-docs/pull/2172
- [x] Publish 0.25.0 to https://unsupported.docs.camunda.io/0.25/ (published in https://github.com/camunda/camunda-platform-docs/releases/tag/0.25.0)
- [ ] https://github.com/camunda/camunda-platform-docs/pull/2199
- [ ] https://github.com/camunda/camunda-platform-docs/pull/2200
```

**Comment by pepopowitz** [comment]
Closed as completed!
