### ISSUE TITLE
Archive v0.26

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#2184]
Archive version 0.26.

## Progress

```[tasklist]
### Tasks
- [x] https://github.com/camunda/camunda-platform-docs/pull/2224
- [x] https://github.com/camunda/camunda-platform-docs/pull/2225
- [x] https://github.com/camunda/camunda-platform-docs/pull/2229
- [x] https://github.com/camunda/camunda-platform-docs/pull/2235
- [x] Isolation step 4: publish 0.26.0 release - published in https://github.com/camunda/camunda-platform-docs/releases/tag/0.26.13
- [x] https://github.com/camunda/camunda-platform-docs/pull/2239
- [x] https://github.com/camunda/camunda-platform-docs/pull/2240
- [x] removal: publish `main` to production - published in https://github.com/camunda/camunda-platform-docs/releases/tag/8.2.23
- [ ] https://github.com/camunda/camunda-platform-docs/pull/2247
```

**Comment by pepopowitz** [comment]
Completed!
